package sh.noro.app.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Slider
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import kotlin.random.Random

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun GeneratorScreen(
    onBack: () -> Unit
) {
    val context = LocalContext.current

    var length by remember { mutableFloatStateOf(16f) }
    var uppercase by remember { mutableStateOf(true) }
    var lowercase by remember { mutableStateOf(true) }
    var numbers by remember { mutableStateOf(true) }
    var symbols by remember { mutableStateOf(true) }

    var generated by remember { mutableStateOf(generatePassword(16, true, true, true, true)) }

    fun regenerate() {
        generated = generatePassword(
            length.toInt(),
            uppercase,
            lowercase,
            numbers,
            symbols
        )
    }

    fun copyToClipboard() {
        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText("Password", generated)
        clipboard.setPrimaryClip(clip)
        Toast.makeText(context, "Password copied", Toast.LENGTH_SHORT).show()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Generator") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                }
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Card(
                modifier = Modifier.fillMaxWidth()
            ) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(16.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = generated,
                        style = MaterialTheme.typography.titleMedium,
                        fontFamily = FontFamily.Monospace,
                        modifier = Modifier.weight(1f)
                    )
                    IconButton(onClick = { regenerate() }) {
                        Icon(Icons.Default.Refresh, contentDescription = "Regenerate")
                    }
                    IconButton(onClick = { copyToClipboard() }) {
                        Icon(Icons.Default.ContentCopy, contentDescription = "Copy")
                    }
                }
            }

            Spacer(modifier = Modifier.height(8.dp))

            Text(
                text = "Length: ${length.toInt()}",
                style = MaterialTheme.typography.titleSmall
            )
            Slider(
                value = length,
                onValueChange = {
                    length = it
                    regenerate()
                },
                valueRange = 8f..64f,
                steps = 55
            )

            Spacer(modifier = Modifier.height(8.dp))

            OptionRow(
                label = "Uppercase (A-Z)",
                checked = uppercase,
                onCheckedChange = {
                    uppercase = it
                    regenerate()
                }
            )

            OptionRow(
                label = "Lowercase (a-z)",
                checked = lowercase,
                onCheckedChange = {
                    lowercase = it
                    regenerate()
                }
            )

            OptionRow(
                label = "Numbers (0-9)",
                checked = numbers,
                onCheckedChange = {
                    numbers = it
                    regenerate()
                }
            )

            OptionRow(
                label = "Symbols (!@#\$%)",
                checked = symbols,
                onCheckedChange = {
                    symbols = it
                    regenerate()
                }
            )

            Spacer(modifier = Modifier.weight(1f))

            Button(
                onClick = { copyToClipboard() },
                modifier = Modifier.fillMaxWidth()
            ) {
                Text("Copy password")
            }
        }
    }
}

@Composable
private fun OptionRow(
    label: String,
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit
) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodyLarge
        )
        Switch(
            checked = checked,
            onCheckedChange = onCheckedChange
        )
    }
}

private fun generatePassword(
    length: Int,
    uppercase: Boolean,
    lowercase: Boolean,
    numbers: Boolean,
    symbols: Boolean
): String {
    val chars = buildString {
        if (uppercase) append("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
        if (lowercase) append("abcdefghijklmnopqrstuvwxyz")
        if (numbers) append("0123456789")
        if (symbols) append("!@#\$%^&*()_+-=[]{}|;:,.<>?")
    }

    if (chars.isEmpty()) return ""

    return (1..length)
        .map { chars[Random.nextInt(chars.length)] }
        .joinToString("")
}
